INSERT INTO `person` (`adress`,`first_name`, `gender`, `last_name`) VALUES 
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes'),
	('Bahia','italo','Male','Lopes');